---

- name: Setup or update development system
  hosts: development
  vars_files: development_vault_encrypted.yml
  become: true
  vars:
    ansible_become_pass: "{{ development_host_sudo_password }}"

  tasks:
    - name: Ensure that essential development packages are installed
      ansible.builtin.package:
        update_cache: true
        name:
          - git
          - vim
          - jq
          - tree
        state: present


- name: Setup pertinent to proxmox
  hosts: proxmox
  vars_files: development_vault_encrypted.yml
  become: true
  vars:
    ansible_become_pass: "{{ development_host_sudo_password }}"

  tasks:
    - name: Install QEMU guest agent
      ansible.builtin.package:
        update_cache: true
        name:
          - qemu-guest-agent
        state: present

    - name: Enable and run QEMU guest agent
      ansible.builtin.service:
        name: qemu-guest-agent.service
        enabled: true
        state: started
