- name: Setup or update development system
  hosts: development
  vars_files: development_vault_encrypted.yml
  become: true
  vars:
    ansible_become_pass: "{{ development_host_sudo_password }}"

  tasks:
    - name: Ensure that essential development packages are installed
      ansible.builtin.apt:
        name:
          - git
          - vim
          - jq
        state: present
