---

- name: Setup or update development system
  hosts: development
  vars_files: development_vault_encrypted.yml
  become: true

  tasks:
    - name: Ensure that essential development packages are installed
      ansible.builtin.package:
        update_cache: true
        name:
          - git
          - vim
          - jq
          - tree
          - bc
        state: present